GEMINI_API_KEY = "sk-your-gemini-key"
bot_token = "123456:ABCDEF..."
chat_id = "987654321"
ADMIN_PASS = "demo123"
DATABASE_URL='postgresql://neondb_owner:npg_oiX4fx6aMmVI@ep-summer-feather-a1ukvtv1-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require'
